baseURL: /
languageCode: en-us
title: Mr Ash Co
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mr Ash Co
  description: "Curious about cybersec, python and hacking"
  keywords: [Blog, Portfolio, CyberSec]
  author: Mr Ash
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "02/01/2006" # January 2, 2006
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  cover:
    linkFullImages: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "Mr Ash Co"
    subtitle: "Curious about cybersec, python & hacking."
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Ash 👋"
    Content: Welcome to my blog, mainly CTF writeups from TryHackMe and videos. I'm curious about cybersec, python & hacking. 

  socialIcons:
    - name: youtube
      url: "https://youtube.com/@mrashco"
    - name: twitter
      url: "https://twitter.com/mrashc0"
    - name: github
      url: "https://github.com/mrashco"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/mrashco/mrash.co/tree/main/content"
    Text: "Suggest Edits" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary
menu:
  main:
    - identifier: now
      name: now
      url: now
      weight: 10
    - identifier: archives
      name: archives
      url: archives
      weight: 20
    - identifier: letters
      name: letters
      url: /letter
      weight: 30
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 40
    - identifier: search
      name: 🔍
      url: /search
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai