baseURL: /
languageCode: en-us
title: Mr Ash Co
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mr Ash Co
  description: "Curious about cybersec, python and hacking"
  keywords: [Blog, Portfolio, CyberSec]
  author: Mr Ash
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "02/01/2006" # January 2, 2006
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  cover:
    linkFullImages: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://p146.p4.n0.cdn.getcloudapp.com/items/Jrum0N6q/4ab8cbb7-d222-4c3c-963d-f0ec6c30568c.jpg?source=viewer&v=db94595858aad20b777e4f130cbe5006"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "mrashco"
    icon: # https://p146.p4.n0.cdn.getcloudapp.com/items/Jrum0N6q/4ab8cbb7-d222-4c3c-963d-f0ec6c30568c.jpg?source=viewer&v=db94595858aad20b777e4f130cbe5006
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "Mr Ash Co"
    subtitle: "Curious about cybersec, python & hacking."
    imageUrl: "https://p146.p4.n0.cdn.getcloudapp.com/items/Jrum0N6q/4ab8cbb7-d222-4c3c-963d-f0ec6c30568c.jpg?source=viewer&v=db94595858aad20b777e4f130cbe5006"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Ash 👋"
    Content: Welcome to my blog, mainly CTF writeups from TryHackMe and videos. I'm curious about cybersec, python & hacking. {{< rawhtml >}}<br><br><script src="https://tryhackme.com/badge/247114"></script><br><br><script src="https://apis.google.com/js/platform.js"></script><div class="g-ytsubscribe" data-channelid="UCXsqs_wm5KIYdugoC5kHZrA" data-layout="default" data-theme="dark" data-count="default"></div>{{< /rawhtml >}}

  socialIcons:
    - name: youtube
      url: "https://youtube.com/@mrashco"
    - name: twitter
      url: "https://twitter.com/mrashc0"
    - name: github
      url: "https://github.com/mrashco"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/mrashco/mrash.co/tree/main/content"
    Text: "Suggest Edits" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary
menu:
  main:
    - identifier: now
      name: now
      url: now
      weight: 10
    - identifier: blog
      name: blog
      url: /blog
      weight: 20
    - identifier: letters
      name: letters
      url: /letter
      weight: 30
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 40
    - identifier: search
      name: 
      post: <svg xmlns="http://www.w3.org/2000/svg" width="17.5" height="17.5" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
      url: /search
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai